export const ADD_TODO_CLICK = 'ADD_TODO_CLICK';
export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED';

export const REMOVE_TODO_CLICK = 'REMOVE_TODO_CLICK';
export const REMOVE_TODO_REQUEST = 'REMOVE_TODO_REQUEST';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_FAILED = 'REMOVE_TODO_FAILED';

export const UPDATE_TODO_CLICK = 'UPDATE_TODO_CLICK';
export const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_FAILED = 'UPDATE_TODO_FAILED';

export const MOVE_TODO = 'MOVE_TODO';
